<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-28 13:17
=======
# Generated by Django 5.2.7 on 2025-10-07 12:40
>>>>>>> 5a07cf1c289e548f0c79e7e5e8f00fd7a886097e

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
=======
        ('plano', '0001_initial'),
>>>>>>> 5a07cf1c289e548f0c79e7e5e8f00fd7a886097e
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_perfil/')),
                ('bio', models.TextField(blank=True, null=True)),
=======
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='plano.plano')),
>>>>>>> 5a07cf1c289e548f0c79e7e5e8f00fd7a886097e
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
