# Generated by Django 5.2.7 on 2025-10-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_plano_assinatura'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfilusuario',
            old_name='foto',
            new_name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_perfil/'),
        ),
    ]
