# Generated by Django 5.2.7 on 2025-10-31 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_rename_foto_perfilusuario_foto_perfil_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='foto_perfil',
            new_name='foto',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='bio',
        ),
    ]
