<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-28 13:17

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.2.7 on 2025-10-07 12:40

>>>>>>> 5a07cf1c289e548f0c79e7e5e8f00fd7a886097e
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 5a07cf1c289e548f0c79e7e5e8f00fd7a886097e
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
<<<<<<< HEAD
                ('duracao', models.CharField(max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanoAtivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_assinatura', models.DateTimeField(auto_now_add=True)),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plano.plano')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
=======
                ('limite_verificacoes', models.IntegerField(default=10)),
>>>>>>> 5a07cf1c289e548f0c79e7e5e8f00fd7a886097e
            ],
        ),
    ]
