<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-10-28 13:17
=======
# Generated by Django 5.2.7 on 2025-10-07 12:40
>>>>>>> 5a07cf1c289e548f0c79e7e5e8f00fd7a886097e

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
<<<<<<< HEAD
                ('status', models.CharField(max_length=20)),
=======
                ('status', models.CharField(max_length=100)),
>>>>>>> 5a07cf1c289e548f0c79e7e5e8f00fd7a886097e
                ('data', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
